<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Execute all xiidra test cases.</description>
   <name>TS-Xiidra</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-28T21:43:10</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>a1402679-f06e-4274-aaaa-225fe6223c22</testSuiteGuid>
   <testCaseLink>
      <guid>1107c66d-3516-4a39-92fd-4f0e1b608977</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shire-Publisher-2.0/TC-Xiidra/TC-Xiidra-Multiplan-Payer-For-PBM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9adae30-0c7d-4a2c-b351-350cf8b9e915</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01ed7b73-eb60-4ff5-af39-177db2af1cdc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7aaf3aa2-0fd3-4092-89b6-def628eab38d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>229d4ca5-d5ce-4bce-9e2e-b332c018df98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9271f3f3-80fa-4b74-af8d-93a15678820d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2006a21-fd33-4043-a658-21f086c06c03</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2125306b-d6ce-4c86-8ea6-05d527a91884</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shire-Publisher-2.0/TC-Xiidra/TC-Xiidra-Multiplan-Formulary-Grid</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>75c0d937-c7b0-4e6b-b51b-4767d740ae37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shire-Publisher-2.0/TC-Xiidra/TC-Xiidra-Single-Plan-Formulary-Grid-With-National-Option</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d97dbf7-334d-48a5-bd26-f097cbc8817f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69578723-80ec-4847-b1aa-3e4bbe8f303e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab522134-6d72-4782-9ec5-8975da16122b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60a27b43-f1a0-46a3-bb85-b98b3216b1cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d46974c-c9be-4d73-bc65-ed139acfa319</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cf4a75e-4ea5-48e6-a9db-f33ae55c24c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>332314fa-2479-4bcd-a2f3-fb9174c20b84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shire-Publisher-2.0/TC-Xiidra/TC-Xiidra-Single-Plan-Formulary-Grid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3da12bb4-8659-40fa-afce-07d97a45436b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0c4908b-bd5d-4df6-a85b-a2da47acc34a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef05c59f-029f-4269-9be1-10d8ab09218f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dcd00b1-649a-4589-bf89-be0810446db1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f835d8f7-ed5a-43ef-8202-d9b507f7fcc5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15b2e8f5-dbef-463b-b40e-9affd1b4ece4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97ea82be-224f-44c5-a056-dc6ab9d42b53</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shire-Publisher-2.0/TC-Xiidra/TC-Xiidra-Multiplan-With-Status</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>62bc7bb8-2ad5-4a34-87ab-15fa0de48d25</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shire-Publisher-2.0/TC-Xiidra/TC-Xiidra-Multiplan-With-Copay</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
