<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Execute all xiidra test cases.</description>
   <name>TS-Xiidra</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-28T21:43:10</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>a1402679-f06e-4274-aaaa-225fe6223c22</testSuiteGuid>
   <testCaseLink>
      <guid>1107c66d-3516-4a39-92fd-4f0e1b608977</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shire-Publisher-2.0/TC-Xiidra/TC-Xiidra-Multiplan-Payer-For-PBM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9adae30-0c7d-4a2c-b351-350cf8b9e915</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01ed7b73-eb60-4ff5-af39-177db2af1cdc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7aaf3aa2-0fd3-4092-89b6-def628eab38d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>229d4ca5-d5ce-4bce-9e2e-b332c018df98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9271f3f3-80fa-4b74-af8d-93a15678820d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2006a21-fd33-4043-a658-21f086c06c03</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2125306b-d6ce-4c86-8ea6-05d527a91884</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shire-Publisher-2.0/TC-Xiidra/TC-Xiidra-Multiplan-Formulary-Grid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d290bf36-15ec-435f-adf5-e3171ecbf033</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c31321b-edb1-494a-a7ef-c44ea2deac5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fee37579-e2c3-46ae-9ae6-e85b206882fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>742a9ee9-b9e2-4a9e-a4fd-fb577c9b6f32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>238a3199-d310-4df3-8686-4a235efc88ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23bda59d-8884-473c-8ef6-b0d334d0191b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>75c0d937-c7b0-4e6b-b51b-4767d740ae37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shire-Publisher-2.0/TC-Xiidra/TC-Xiidra-Single-Plan-Formulary-Grid-With-National-Option</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d97dbf7-334d-48a5-bd26-f097cbc8817f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69578723-80ec-4847-b1aa-3e4bbe8f303e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab522134-6d72-4782-9ec5-8975da16122b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60a27b43-f1a0-46a3-bb85-b98b3216b1cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d46974c-c9be-4d73-bc65-ed139acfa319</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cf4a75e-4ea5-48e6-a9db-f33ae55c24c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>332314fa-2479-4bcd-a2f3-fb9174c20b84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shire-Publisher-2.0/TC-Xiidra/TC-Xiidra-Single-Plan-Formulary-Grid</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3da12bb4-8659-40fa-afce-07d97a45436b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0c4908b-bd5d-4df6-a85b-a2da47acc34a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef05c59f-029f-4269-9be1-10d8ab09218f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dcd00b1-649a-4589-bf89-be0810446db1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f835d8f7-ed5a-43ef-8202-d9b507f7fcc5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15b2e8f5-dbef-463b-b40e-9affd1b4ece4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97ea82be-224f-44c5-a056-dc6ab9d42b53</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shire-Publisher-2.0/TC-Xiidra/TC-Xiidra-Multiplan-With-Status</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>443d9544-a056-4e18-97e7-2d60727fc0a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70598a9d-6772-48de-be3b-5caebf345f4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db6ea410-9242-42ec-b25d-88d3bc3536c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce6cc6ec-b809-4147-8d11-35dc741ee652</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de654a76-8be5-472b-be0e-387af9358dfc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62bc7bb8-2ad5-4a34-87ab-15fa0de48d25</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shire-Publisher-2.0/TC-Xiidra/TC-Xiidra-Multiplan-With-Copay</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01c47976-bc3f-409a-8d4f-84d8b04c7c35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bd00d39-1235-48f4-b2c2-f6ca8e6e919b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc39ec1b-9ec9-4978-9eb8-0728cb10d02a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b0cc479-6937-4474-807a-186f9718e127</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5eb40b89-516d-4dd9-b5f1-ccffbb8a6d8e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
