<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>payerStep</name>
   <tag></tag>
   <elementGuidId>92231cf1-1277-4bbe-9d91-26cf8af0ad85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='payer-panel']//p[@class='pull-left']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='payer-panel']//p[@class='pull-left']</value>
   </webElementProperties>
</WebElementEntity>
