<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectCommercialPayer</name>
   <tag></tag>
   <elementGuidId>eee4ea08-6e37-423f-8d3a-a2e88a31c1b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@id='commercial-payers-table']//td[contains(text(),'${Variable}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@id='commercial-payers-table']//td[contains(text(),'${Variable}')]</value>
   </webElementProperties>
</WebElementEntity>
