<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectPayerType</name>
   <tag></tag>
   <elementGuidId>dd3ed691-252e-47ac-906b-75c0e00819c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='payer-display']//button[@type='button'][contains(text(),'${Variable}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='payer-display']//button[@type='button'][contains(text(),'${Variable}')]</value>
   </webElementProperties>
</WebElementEntity>
