<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Executing &quot;Xiidra-Multiplan-Payer-For-PBM&quot; for multiple set of data from excel file.</description>
   <name>TS01-Xiidra-Multiplan-Payer-For-PBM</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-12-04T14:03:27</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>1f45dba0-2e02-4f26-90f1-81439f56fbb8</testSuiteGuid>
   <testCaseLink>
      <guid>9153b22c-3788-47b6-ab7c-3a30edda4942</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shire-Publisher-2.0/TC-Xiidra/TC-Xiidra-Multiplan-Payer-For-PBM</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3e568b96-2e2f-4c6d-aa48-969c4dcddfa7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TS-Xiidra-Data-Driven/TS01-Xiidra-Multiplan-Payer-For-PBM-CSV</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9adae30-0c7d-4a2c-b351-350cf8b9e915</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3e568b96-2e2f-4c6d-aa48-969c4dcddfa7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>locationName</value>
         <variableId>01ed7b73-eb60-4ff5-af39-177db2af1cdc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7aaf3aa2-0fd3-4092-89b6-def628eab38d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3e568b96-2e2f-4c6d-aa48-969c4dcddfa7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>payerNames</value>
         <variableId>229d4ca5-d5ce-4bce-9e2e-b332c018df98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3e568b96-2e2f-4c6d-aa48-969c4dcddfa7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>planNames</value>
         <variableId>9271f3f3-80fa-4b74-af8d-93a15678820d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3e568b96-2e2f-4c6d-aa48-969c4dcddfa7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>locationType</value>
         <variableId>a2006a21-fd33-4043-a658-21f086c06c03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64ddc963-d22b-4efd-9cee-25fab68a681e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
