<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Execute test case for different data sets from excel file</description>
   <name>TS02-Xiidra-Single-Plan-Formulary-Grid</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-29T15:18:09</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c212053a-6ce2-4703-933b-23aa935aabde</testSuiteGuid>
   <testCaseLink>
      <guid>50866041-cc98-437e-80f2-7b511ab6b146</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shire-Publisher-2.0/TC-Xiidra/TC-Xiidra-Single-Plan-Formulary-Grid</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e29c840f-a0e6-4a8d-82a3-6b4d2dacf06c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TS-Xiidra-Data-Driven/TS02-Xiidra-Single-Plan-Formulary-Grid</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3da12bb4-8659-40fa-afce-07d97a45436b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e29c840f-a0e6-4a8d-82a3-6b4d2dacf06c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>locationType</value>
         <variableId>e0c4908b-bd5d-4df6-a85b-a2da47acc34a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e29c840f-a0e6-4a8d-82a3-6b4d2dacf06c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>locationName</value>
         <variableId>ef05c59f-029f-4269-9be1-10d8ab09218f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e29c840f-a0e6-4a8d-82a3-6b4d2dacf06c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>planOrPayer</value>
         <variableId>6dcd00b1-649a-4589-bf89-be0810446db1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e29c840f-a0e6-4a8d-82a3-6b4d2dacf06c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>planOrPayerName</value>
         <variableId>f835d8f7-ed5a-43ef-8202-d9b507f7fcc5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
