<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS03-Xiidra-Single-Plan-Formulary-Grid-With-National-Option</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-29T18:18:03</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>dec7df3f-c103-4460-9070-d5443940a74f</testSuiteGuid>
   <testCaseLink>
      <guid>ff5df6c1-6d48-41ef-b640-0a6881fc36c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shire-Publisher-2.0/TC-Xiidra/TC-Xiidra-Single-Plan-Formulary-Grid-With-National-Option</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>86c68475-57cb-45a3-a4df-cc5ea41d438b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TS-Xiidra-Data-Driven/TS03-Xiidra-Single-Plan-Formulary-Grid-With-National-Option</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d97dbf7-334d-48a5-bd26-f097cbc8817f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69578723-80ec-4847-b1aa-3e4bbe8f303e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>86c68475-57cb-45a3-a4df-cc5ea41d438b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>planOrPayer</value>
         <variableId>ab522134-6d72-4782-9ec5-8975da16122b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>86c68475-57cb-45a3-a4df-cc5ea41d438b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>planOrPayerName</value>
         <variableId>60a27b43-f1a0-46a3-bb85-b98b3216b1cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d46974c-c9be-4d73-bc65-ed139acfa319</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cf4a75e-4ea5-48e6-a9db-f33ae55c24c1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
