<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS06-Xiidra-Multiplan-With-Status</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-12-04T15:06:16</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>849e754f-96bf-4840-849b-06df25d91e05</testSuiteGuid>
   <testCaseLink>
      <guid>2756b5a6-d6b9-4f26-a467-7d7d0730a593</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shire-Publisher-2.0/TC-Xiidra/TC-Xiidra-Multiplan-With-Status</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2ba70915-033d-4b97-813e-ad5e4a173155</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TS-Xiidra-Data-Driven/TS06-Xiidra-Multiplan-With-Status</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e310095-21a2-407d-8596-fd0f99cf7142</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>560fc483-d50c-47d9-a00c-1837812a79e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10681d2e-1512-453c-94b9-9d4e065e2da9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>419412da-5fc3-4914-b9ce-2c776cf2fbe3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>191f946c-d1e8-40b3-b5ae-61e40a1d36fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef05bd45-d619-4542-aee0-02b6b75ff768</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
