<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>calloutStep</name>
   <tag></tag>
   <elementGuidId>ffe2aa33-eec7-4793-b89e-14ce3141d43a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='callout-panel']//p[@class='pull-left']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='callout-panel']//p[@class='pull-left']</value>
   </webElementProperties>
</WebElementEntity>
