<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectMedicarePlan</name>
   <tag></tag>
   <elementGuidId>f1dbe4e3-e613-4f90-9787-6bdd4eeba4c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@id='medicare-table']//td[contains(text(),'${Variable}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@id='medicare-table']//td[contains(text(),'${Variable}')]</value>
   </webElementProperties>
</WebElementEntity>
