<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>copayStep</name>
   <tag></tag>
   <elementGuidId>46dc2b38-986d-48e1-bdf0-82ac9fbe7b24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='copay-panel']//p[@class='pull-left']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='copay-panel']//p[@class='pull-left']</value>
   </webElementProperties>
</WebElementEntity>
