<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectMSA</name>
   <tag></tag>
   <elementGuidId>069d9202-67bc-4102-94a9-d1f96a060595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@id='twotier-selections']//li//input[@data-value='${Variable}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@id='twotier-selections']//li//input[@data-value='${Variable}']</value>
   </webElementProperties>
</WebElementEntity>
