<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectStateForMsa</name>
   <tag></tag>
   <elementGuidId>1572ecfb-4994-4c93-bb43-67aec6190d9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@id='twotier-selector']//li//a[@href='#'][contains(text(),'${Variable}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@id='twotier-selector']//li//a[@href='#'][contains(text(),'${Variable}')]</value>
   </webElementProperties>
</WebElementEntity>
